apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pwqi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-pwqi@sha256:2a4de1066f59edd75ea900d43eb812c9ba7827e5c258c937b9edfbf2e0f59399
        name: my-nodejs
        resources: {}
status: {}
